In [7]:
import numpy as np

arr= np.random.randint(low=0, high=100, size=15)
arr

array([65, 60,  0, 57,  2, 92,  4, 21, 58,  3, 58, 87, 80, 68,  4])

In [8]:
arr.max()

92

In [11]:
np.where(arr==92)

(array([5], dtype=int64),)

In [12]:
arr[arr>10]

array([65, 60, 57, 92, 21, 58, 58, 87, 80, 68])

In [17]:
lista=arr[(arr>10) & (arr<30)]
lista

array([21])

Nosso próximo foco serão as matrizes. Faça o que se pede:

a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando o np.linspace();

b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;

c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método np.matmul().

In [75]:
matrix=np.array(np.linspace(0, 100, num=6)).reshape(3,2)
matrix
matrix.t

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

In [57]:
rand_matrix=np.random.randint(low=0, high=100, size=10).reshape(5,2)
rand_matrix

array([[77, 71],
       [83, 40],
       [24, 52],
       [37, 77],
       [28, 91]])

In [81]:
array=np.array(([1,1,1],[1,1,1])).reshape(2,3)
np.matmul(matrix,array)


array([[ 20.,  20.,  20.],
       [100., 100., 100.],
       [180., 180., 180.]])

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [85]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
[arr[i] for i in range(2)]

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

Entrada: [maçã, uva, morango, melancia, acelga]

Saída: [maçã, morango, melancia]

In [92]:
lista = ['maçã', 'uva', 'morango', 'melancia', 'acelga']
conditions = 
array=np.array(lista)
for fruit in array
    if (fruit[0]=='a') or (fruit[0]=='e') or (fruit[0]=='i') or (fruit[0]=='o') or (fruit[0]=='u'):
        
    

array(['maçã', 'uva', 'morango', 'melancia', 'acelga'], dtype='<U8')